# ==============================
# 使用 Weaviate 官方镜像
# ==============================
FROM cr.weaviate.io/semitechnologies/weaviate:latest

# 维护者信息
LABEL maintainer="Plumess"

# 示意暴露服务端口（并未实际映射）
EXPOSE 8080
EXPOSE 50051
