# ==============================
# vLLM 推理后端 搭建
# ==============================
  vllm:
    build:
      context: vLLM/
      dockerfile: ${DOCKERFILE_DEVICE}
      args:
        max_jobs: 8  # 设置并行编译的最大线程数
        RUN_WHEEL_CHECK: "false"  # 关掉！关掉！不然会浪费你人生中的几千秒
    image: vllm:${DEVICE}-${VLLM_VERSION}
    container_name: vllm
    volumes:
      # 动态挂载本地的模型目录到容器内部
      - ${LLM_MODEL_VOLUME:-../LLMCore/pretrained/models}:/download/models
      - ${EMBEDDING_MODEL_VOLUME:-../LLMCore/pretrained/embedding}:/download/embedding
    networks:
      - mimirnet
    ports:
      - 24900:8000
    restart: unless-stopped
    command: sleep infinity