services:
# ==============================
# LLMCore 模块搭建
# ==============================
  llmcore:
    build:
      context: ../
      dockerfile: Docker/LLMCore/${DOCKERFILE_DEVICE}
      target: product
      args:
        BUILDKIT_INLINE_CACHE: '1'
    image: llmcore:${DEVICE}-${LLMCORE_VERSION}
    container_name: llmcore
    volumes:
      - ${LLMCORE_VOLUME:-../LLMCore}:/app/LLMCore  # 动态挂载 LLMCore
      - ${GLOBAL_CONFIG_VOLUME:-../config}:/app/config
    networks:
      - mimirnet  # 统一使用自建的 MimirNet 网络通信
    ports:
      - 24910:24910
    shm_size: '16gb'
    env_file:
      - ./LLMCore/llmcore.env
    restart: unless-stopped
    command: sleep infinity
    environment:
      - DEVICE=${DEVICE}

# ==============================
# Weaviate 向量数据库 搭建
# ==============================
  weaviate:
    build:
      context: ../
      dockerfile: Docker/Weaviate/Dockerfile
      args:
        WEAVIATE_VERSION: ${WEAVIATE_VERSION}
    image: weaviate:${WEAVIATE_VERSION}
    container_name: weaviate
    volumes:
      - ${WEAVIATE_DATA_VOLUME:-./Weaviate/data}:/var/lib/weaviate
    networks:
      - mimirnet
    ports:
      - 24980:8080
      - 50052:50051
    restart: unless-stopped
    env_file:
      - ./Weaviate/weaviate.env
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http

networks:
  mimirnet:
    driver: bridge

# ./build.sh